<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPNRIIu1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPNRIIu1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPNRIIu1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPNRIIu1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPNRIIu1\App_KernelDevDebugContainer([
    'container.build_hash' => 'PNRIIu1',
    'container.build_id' => 'bbdf12f5',
    'container.build_time' => 1627650495,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPNRIIu1');
